name: Building-Apk

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'yarn'
      - name: Run install
        run: yarn
    
        
      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' 
          java-version: '17'
          cache: 'gradle'

  
      - name: Build
        run: ./gradlew assembleRelease
        working-directory: ./android
        

      - name: Upload APK Release
        uses: actions/upload-artifact@v3
        with:
          name: Apk release generated
          path: android\app\build\outputs\apk\release
      
      # - name: Save bundle file
      #   uses: actions/upload-artifact@v3
      #   continue-on-error: true
      #   with:
      #     name: bundle-file
      #     path: android/app/build/ASSETS/createBundleReleaseJsAndAssets/index.android.bundle
