name: Building-Apk

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Git checkout ##
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'  # Define Node version ##
          cache: 'yarn'
          
      - name: Run install
        run: yarn
    
      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' 
          java-version: '17'   # Define Java version  ##
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x ./android/gradlew  # Grant permission to gradlew  ##

      - name: Build APK
        run: ./gradlew assembleRelease --stacktrace  # Build release APK with stacktrace for better error reporting  ##
        working-directory: ./android
        
      - name: Find APK files
        run: find . -name "*.apk" -print  # Find and print the path to all APK files in the project ##

      - name: List APK files
        run: ls -R android/app/build/outputs/apk/release  # List files to ensure APK exists  ##

      - name: Upload APK Release
        uses: actions/upload-artifact@v3
        with:
          name: Apk release generated
          path: android/app/build/outputs/apk  # Store APK in this path  ##
      
      # - name: Save bundle file
      #   uses: actions/upload-artifact@v3
      #   continue-on-error: true
      #   with:
      #     name: bundle-file
      #     path: android/app/build/ASSETS/createBundleReleaseJsAndAssets/index.android.bundle
